Feature/3 카카오 로그인 & 회원가입
9in-team/Backend pull request #4
Opened 2023-02-09 13:42 UTC by choikangheon

- Spring Security를 통한 카카오 로그인 처리
- 프론트와 통신하여 회원 가입 처리

2023-02-10 01:47 UTC, deepredk requested changes

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/domain/user/User.kt
> +    fun prePersist() {
fun prePersist() = userRole ?: "USER"
한 줄로 가능

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/domain/user/User.kt
> +    fun getRoleList(): MutableList<out Any?> {
코틀린에서 split의 반환형은 String[]이 아닌 List<String>이고

fun getRoleList() = userRole.split(",") 이걸로 충분하지 않아?


궁금한 점
1. <out Any?>는 왜 필요한거야?
2. 가변(Mutable)리스트 말고 불변(Imuutable)리스트로 다뤄도 충분하지 않아?
3. String?으로 한 이유는 뭐야? null이 들어갈 가능성이 있어?

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/domain/user/User.kt
> +    var userId: Long? = null,
val userId: Long,
요렇게해도 충분하지 않아?

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/infrastructure/kakao/service/KakaoApiService.kt
> +    fun convertKakaoUserInfoDTO(jsonData: String): KakaoDetail {
json을 DTO로 변환하는 역할을

KakaoDetail.fromJson(json: String)
요렇게 DTO쪽에 맡겨버리는건 어때

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/infrastructure/kakao/service/KakaoApiService.kt
> +        val con: HttpURLConnection = url.openConnection() as HttpURLConnection
val con = url.openConnection() as HttpURLConnection
타입이 확실하기때문에 이렇게도 가능

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/presentation/UserController.kt
> +    fun reqJoinUser(@RequestBody joinUserDTO: ReqJoinUserDTO) {
메서드 이름 reqJoinUser -> join
요렇게 줄여버리는거 어때

2023-02-10 01:47 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/application/user/dto/UserDTO.kt
> +data class ReqLoginDTO(var kakaoAccessToken: String)
Request에 쓰이는 DTO는
LoginRequest

Response에 쓰이는 DTO는
LoginResponse

이렇게 이름 규칙 정하는거 어때?

2023-02-10 01:49 UTC, deepredk requested changes

2023-02-10 01:49 UTC, deepredk commented on src/main/kotlin/team/guin/monolithic/application/user/service/UserService.kt
> +    fun joinUser(userDTO: ReqJoinUserDTO) {
join으로 메서드 이름 줄여버리는거 어때

2023-02-10 01:56 UTC, deepredk commented
아 패키지 구조 이제 봤는데
presentation application domain infra 레이어드 아키텍처에 대한 이해가 좀 많이 부족한 거 같아
한번 따로 공부해줘

전에 줬던 Bulls-And-Cows 이 소스 참고하면 좋을거야

2023-02-12 14:31 UTC, choikangheon reviewed
카카오 로그인/회원가입  1차 코드리뷰 반영 완료
추가적으로 검토 필요한 부분 커밋 남겨두었습니다

2023-02-12 14:31 UTC, choikangheon commented on src/main/kotlin/team/guin/monolithic/domain/user/User.kt
> +    fun getRoleList(): MutableList<out Any?> {
1,2,3 모두 코틀린의 이해도 부족에서 일어난 것 같습니다 :( 
자바와 동일하게 split 시에, String 형 배열이 반환 되는줄 알았습니다 
앞으로 리스트 반환형으로 이해하고 사용하면 될 것 같습니다!

2023-02-13 13:28 UTC, merged