[#28] User Entity 및 UserRepository 최종 리팩토링 반영
9in-team/Backend pull request #53
Opened 2023-03-01 10:24 UTC by choikangheon

- User Roles 생성자에서 제외
  - 해당 수정으로 인한 테스트 코드 수정

2023-03-01 11:33 UTC, deepredk approved these changes
rebase 꼬인거 푸느라 고생 많으셨습니다 ㅎㅎ

2023-03-01 11:33 UTC, deepredk commented on domain/src/main/kotlin/team/guin/domain/account/Account.kt
>      var imageId: String,
```
var email: String, // UNIQUE 100자제한
var nickname: String, // UNIQUE 30자제한
var imageId: String, // 1000자 제한?
```
저희 회의에서 이야기 했던대로 위와 같이 제약조건 적용되면 좋을 것 같습니다!

2023-03-01 11:33 UTC, deepredk commented on api/src/test/kotlin/team/guin/account/AccountApiRepositoryTests.kt
>              result?.imageId shouldBe "imageId"
```kt
// as-is
result?.nickname shouldBe "nickname"
result?.imageId shouldBe "imageId"
// to-be
val nickname = "nickname"
val imageId = "imageId"
result?.nickname shouldBe nickname
result?.imageId shouldBe imageId
```

이미 main에 Merge된 코드에 대한 피드백이긴한데
위와 같이 리터럴 값을 변수로 감싸주면
혹시나 실수로 nick'**an**'me 식으로 오타가 나서 의도치않은 테스트 결과가 나오는 상황을 방지할 수 있을 것 같습니다!

2023-03-01 13:07 UTC, cousim46 approved these changes

2023-03-01 13:14 UTC, cousim46 requested changes
고생하셨습니다~ 그런데 충돌이 발생하고 있네요!

2023-03-01 13:16 UTC, choikangheon commented on domain/src/main/kotlin/team/guin/domain/account/Account.kt
>      var imageId: String,
해당 사항 추가 반영하겠습니다 감사합니다 :)

2023-03-01 14:46 UTC, choikangheon reviewed
충돌 해결완료하였습니다.

2023-03-02 00:43 UTC, cousim46 approved these changes

2023-03-04 07:11 UTC, merged