GlobalExceptionHandler/Resolver 기본 구현
9in-team/Backend pull request #67
Opened 2023-03-12 07:10 UTC by choikangheon

resolve #64 
- GlobalExceptionHandler/Resolver 구현 및 공통 응답
- exceptionHandler 통한 MismatchedInputException을 정형화된 메세지
- 잘못된 json 요청시 MethodArgumentNotValidException 예외처리

2023-03-16 10:43 UTC, deepredk commented on web-common/src/main/kotlin/team/guin/webcommon/exception/response/ErrorResponse.kt
> +    val status: Int,
상태 코드는 Http Response 첫 행에도 드러나므로 빼도 괜찮을 것 같습니다!

2023-03-16 11:05 UTC, choikangheon commented on web-common/src/main/kotlin/team/guin/webcommon/exception/response/ErrorResponse.kt
> +    val status: Int,
Status 변수 말씀하시는 것 맞을까요?
지금 생각해보니 Header 부분에 담겨 있어, 굳이 필요하지 않을 것 같네요
해당 부분 삭제처리하겠습니다. 감사합니다

2023-03-22 00:51 UTC, cousim46 requested changes
구현하시느라 고생 많으셨습니다!!

2023-03-22 00:51 UTC, cousim46 commented on web-common/src/main/kotlin/team/guin/webcommon/exception/CommonExceptionCode.kt
> +    DUPLICATE_EMAIL(HttpStatus.BAD_REQUEST, "중복된 이메일입니다. 다시 입력해주세요."),
이거에 대해 저희끼리 회의할게 있었는데 아직 결정을 못한거 같습니다.
1. 도메인별로 에러코드를 생성할지
2. 한곳에서 관리할지
만약 2번으로 할 시 DUPLICATE_EAMIL은 Account에 대한거니 DUPLICATE_ACCOUNT_EMAIL 이렇게 짓는건 어떨까요?
@deepredk @choikangheon

2023-03-22 00:51 UTC, cousim46 commented on web-common/src/main/kotlin/team/guin/webcommon/exception/example/ExampleExceptionController.kt
> +    @GetMapping("/exception/duplicate")
컨틀롤러 클래스명이 Exception에 대한 이름같은데 @RequestMapping("/common/example/exception")으로 하시는건 어떨까요 (:

2023-03-26 10:52 UTC, choikangheon commented on web-common/src/main/kotlin/team/guin/webcommon/exception/CommonExceptionCode.kt
> +    DUPLICATE_EMAIL(HttpStatus.BAD_REQUEST, "중복된 이메일입니다. 다시 입력해주세요."),
해당 부분 금일 회의에서 한곳에서 통일하였습니다.
DUPLICATE_ACCOUNT_EMAIL 로 수정하겠습니다.

2023-03-26 10:53 UTC, choikangheon commented on web-common/src/main/kotlin/team/guin/webcommon/exception/example/ExampleExceptionController.kt
> +    @GetMapping("/exception/duplicate")
해당 내용 반영하겠습니다 :)

2023-03-31 07:39 UTC, loadkrnis reviewed
테스트 코드 잘 짜셨네요 ㅎㅎ 👍

2023-03-31 07:39 UTC, loadkrnis commented on web-common/src/main/kotlin/team/guin/webcommon/exception/response/ErrorResponse.kt
> +    constructor(error: String, message: Map<String, String>?) : this(now(), error, message)
companion object method로 만들면 인스턴스를 생성할 때 어떤 인스턴스를 생성하는지도 표현할 수 있을 것 같은데 constuctor를 사용하신 이유가 있을까요? 

```kt
companion object {
   fun createWithMessage( .. ): ErrorResponse {
      ..
   }

   fun create( .. ): ErrorResponse {
      ..
   }
}
```

2023-03-31 07:39 UTC, loadkrnis commented on api/src/main/kotlin/team/guin/account/AccountApiController.kt
> +        @RequestBody @Valid
@Valid를 class 위에 작성하시는게 어떠실까요?

```kt
@Valid
class AccountApiController( .. )
```

2023-03-31 07:39 UTC, loadkrnis commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +        }
테스트 엄청 잘 짜셨네요 👍

이거 validator만 혹시 아래와 같이 바꾸시는거 어떠실까요? 

```kt
// beforeSpec 제거
val validator = Validation.buildDefaultValidatorFactory().validator
// 기타 ko 설정도 추가되어야함
```
에러메세지를 한국어로 바꿔놓고 테스트하니까 좋네요

2023-03-31 07:39 UTC, loadkrnis commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +            violations.first().messageTemplate shouldBe "{javax.validation.constraints.NotBlank.message}"
이거 문자열 그대로 써주시면 좋을 것 같아요.
```kt
 violations.first().messageTemplate shouldBe "공백일 수 없습니다."
```
테스트 코드만 보고 바로 이해하기 쉬울 것 같아서요 ㅎㅎ

2023-03-31 07:39 UTC, loadkrnis commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +                // given
given when then 한줄씩 띄어주시면 좋을 것 같아요 ㅎㅎ

```kt
// given
something

// when 
something

// then
something
```

2023-03-31 07:39 UTC, loadkrnis commented on web-common/src/main/kotlin/team/guin/webcommon/exception/GlobalExceptionHandler.kt
> +class GlobalExceptionHandler {
해당 클래스를 사용하는 테스트 코드가 빠진 것 같습니다 🥲

2023-04-03 12:29 UTC, choikangheon commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +        }
해당 부분 오프라인으로 진행하여 설명드리겠습니다.

**이슈** 

_아래 코드를 통해 beforeSpec을 제거하였습니다.
해당 부분 처럼 변경하였던 이유는, beforeSpec을 사용시, 매 Spec 마다 새로운 객체를 생성한다는 문제점이 있었습니다._
```
     val   validator = LocalValidatorFactoryBean().apply {
            setValidationMessageSource(
                org.springframework.context.support.ResourceBundleMessageSource().apply {
                    setBasename("classpath:ValidationMessages_ko")
                    setDefaultEncoding("UTF-8")
                },
            )
            afterPropertiesSet()
        }
```
**하지만**
위 코드  같은 경우 로컬 환경의 나라(언어)를 따라 가기에, 매번 Korea(한국어)설정을 매 테스트마다 설정을 해야되었습니다.

**해결방법**

 - yml 설정을 통한 언어 설정 
 
```
spring:
  messages:
    basename: ValidationMessages_ko
```

2023-04-03 12:30 UTC, choikangheon commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +                // given
해당 부분 수정 완료하였습니다. 감사합니다 :)

2023-04-03 12:31 UTC, choikangheon commented on api/src/test/kotlin/team/guin/account/dto/AccountJoinRequestValidationTest.kt
> +            violations.first().messageTemplate shouldBe "{javax.validation.constraints.NotBlank.message}"
해당 부분 언어 설정 이슈가 있어서, 위와 같이 작성하였지만
언어 default 설정 완료하였습니다.
해당 부분 수정하겠습니다 : )

2023-04-06 10:57 UTC, cousim46 reviewed
구현하시느라 고생하셨습니다!

2023-04-06 10:57 UTC, cousim46 commented on web-common/src/main/kotlin/team/guin/webcommon/exception/CommonExceptionCode.kt
> +    DUPLICATE_ACCOUNT_EMAIL(HttpStatus.BAD_REQUEST, "중복된 이메일입니다. 다시 입력해주세요."),
"중복된 이메일입니다. 다시 입력해주세요." 보다는 "중복된 이메일입니다."로 하는게 어떠신지요?

2023-04-06 10:57 UTC, cousim46 commented on web-common/src/main/kotlin/team/guin/webcommon/exception/GlobalExceptionHandler.kt
> +                is FieldError -> error.field to (error.defaultMessage ?: "유효하지 않은 필드입니다.")
"MethodArgumentNotValidException"이 발생하면 NotBlank, Email 등 기본적으로 제공해주는 디폴트 메시지가 있는데 
```
?: "유효하지 않은 필드입니다."
```
이 부분이 필요할까 싶습니다!

2023-06-04 12:16 UTC, loadkrnis commented on web-common/src/main/kotlin/team/guin/webcommon/exception/GlobalExceptionHandler.kt
> +                is FieldError -> error.field to (error.defaultMessage ?: "유효하지 않은 필드입니다.")
혹시라도 없을 경우 런타임에서 터질까봐 넣으면 좋을 거라고 생각했어요 ㅎㅎ

2023-07-02 11:02 UTC, cousim46 approved these changes

2023-12-14 15:04 UTC, shinseongsu reviewed
테스트 코드 짜는 모습 너무 보기 좋았습니다 😄 
리뷰 남겼는데 천천히 봐주시면 감사하겠습니다

2023-12-14 15:04 UTC, shinseongsu commented on web-common/src/main/kotlin/team/guin/webcommon/exception/response/ErrorResponse.kt
> +    val message: Map<String, String>,
message 가 Map으로 되어 있는데 여러 메시지를 반환할 수 있어서 그런걸까요?

2023-12-14 15:04 UTC, shinseongsu commented on web-common/src/test/kotlin/team/guin/webcommon/exception/GlobalExceptionHandlerTest.kt
> +            "중복된 이메일 CommonException 발생하면 GlobalException 포맷으로 변경한다. " {
테스트 코드에는 개발자만 아는 ***Exception 이 발상한다. 보다는 "중복된 이메일 데이터가 들어오면 에러를 반환한다." 라는 표현이 더 좋을 것같아요

2023-12-17 01:45 UTC, shinseongsu commented
api/src/main/kotlin/team/guin/account/AccountApiController.kt
api/src/main/kotlin/team/guin/account/dto/AccountJoinRequest.kt

두개 파일 충돌 나고 있는데 확인해주시면 감사하겠습니다 😄

2023-12-17 05:09 UTC, merged