모집글 목록 (GET /team)
9in-team/Backend pull request #84
Opened 2023-05-30 10:39 UTC by cousim46

- 등록되어 있는 팀들을 조회하는 API입니다.
- 조회 조건에 study, project,전체가 있어 queryDsl을 이용하여 동적 쿼리로 구현하였습니다.

2023-06-04 12:39 UTC, loadkrnis reviewed
고생하셨습니다 ㅎㅎ
전체적으로 깔끔하시네요!!

2023-06-04 12:39 UTC, loadkrnis commented on api/src/main/kotlin/team/guin/team/QueryDslConfig.kt
> +    @PersistenceContext val entityManager: EntityManager,
PersistenceContext 사용한거 좋네요 ㅎㅎ

2023-06-04 12:39 UTC, loadkrnis commented on api/src/test/kotlin/team/guin/team/TeamApiServiceTest.kt
> +    }
find 해서 존재하는지 여부만 확인할게 아니라 id 값이 일치하는게 존재하는지 확인하면 좋을 것 같아요!
```kt
        "subjectType이 PROJECT이면 PROJECT인 팀만 조회한다." - {
            // given
            val subjectType: SubjectType = SubjectType.PROJECT
            val leader: Account = accountApiRepository.createAccount()
            val projectTeam = teamApiRepository.createTeam(leader = leader, subjectType = SubjectType.PROJECT)
            teamApiRepository.createTeam(leader = leader, subjectType = SubjectType.STUDY)

            // when
            val teams: List<Team> = teamApiService.findAllBySubjectType(subjectType = subjectType)

            // then
            teams.find { it.subjectType == SubjectType.STUDY } shouldBe null
            teams.first { it.subjectType == SubjectType.PROJECT }.id shouldNotBe projectTeam.id
        }
```
모든 검증문에 null만 있으니까 무엇을 찾는지 한눈에 보기 조금 어려운 것 같아서요 ㅎㅎ

2023-06-04 12:39 UTC, loadkrnis commented on build.gradle.kts
> +    kotlin("kapt") version "1.4.10"
`kapt`는 뭘까용?

2023-06-04 12:39 UTC, loadkrnis commented on build.gradle.kts
> +    }
이것도 어떤 역할을 하는지 궁금해요 ㅎㅎ

2023-06-04 12:39 UTC, loadkrnis commented on api/src/test/kotlin/team/guin/team/TeamApiServiceTest.kt
> +    }
앗 이거 진혼님이 FreeSpec에서 사용할 수 있는 방법 슬랙에서 말씀해주셨는데 이미지 첨부해드릴게요!
![image](https://github.com/9in-team/Backend/assets/45731301/0e20e11f-456d-4975-aa97-57106fda7ad1)

2023-06-04 12:39 UTC, loadkrnis reviewed
고생하셨습니다 ㅎㅎ
전체적으로 깔끔하시네요!!

2023-06-05 08:15 UTC, deepredk approved these changes
고생하셨습니다 😄

2023-06-05 08:15 UTC, deepredk commented on api/src/main/kotlin/team/guin/team/dto/TeamDetail.kt
> +        fun toDetail(teams: List<Team>): List<TeamDetail> {
별건 아닌데 toDetailList로 이름 변경하면 좋을 것 같습니다!
나중에 Team->TeamDetail 변환하는 함수 필요할 때 이름이 겹칠 것 같아서요

2023-06-05 10:54 UTC, cousim46 commented on build.gradle.kts
> +    kotlin("kapt") version "1.4.10"
해당 설정은 QueryDSL을 사용하기 위한 설정입니다!!

2023-06-05 10:54 UTC, cousim46 commented on build.gradle.kts
> +    }
해당 설정은 QueryDSL을 사용하기 위한 설정입니다!!

2023-06-05 10:54 UTC, cousim46 commented on api/src/main/kotlin/team/guin/team/QueryDslConfig.kt
> +    @PersistenceContext val entityManager: EntityManager,
감사합니다 ㅎㅎ

2023-06-06 11:50 UTC, choikangheon requested changes
고생 많으셨습니다 :) 
DTO 클래스 관련하여, 한가지 확인 요청 남겼습니다!

2023-06-10 16:27 UTC, cousim46 commented on api/src/test/kotlin/team/guin/team/TeamApiServiceTest.kt
> +    }
감사합니다 (:

2023-06-16 13:25 UTC, deepredk approved these changes
추가 커밋 확인했습니다!

2023-06-21 14:05 UTC, choikangheon approved these changes
고생많으셨습니다~

2023-07-04 00:53 UTC, loadkrnis approved these changes

2023-07-04 03:31 UTC, merged